rails_app/config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
	# https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
  resources :snippets

  authenticate :user do
		get 'evaluations/consent', to: 'evaluations#consent'
		post 'evaluations/record_consent', to: 'evaluations#record_consent'
		get 'evaluations/questionnaire', to: 'evaluations#questionnaire'
		post 'evaluations/record_questionnaire', to: 'evaluations#record_questionnaire'
		get 'evaluations/tutorial', to: 'evaluations#tutorial'
		post 'evaluations/record_tutorial_quiz', to: 'evaluations#record_tutorial_quiz'
		get 'evaluations/tasks', to: 'evaluations#tasks'
		get 'evaluations/task', to: 'evaluations#task'
		post 'evaluations/task_finish', to: 'evaluations#task_finish'
		get 'evaluations/task_questionnaire', to: 'evaluations#task_questionnaire'
		post 'evaluations/record_task_questionnaire', to: 'evaluations#record_task_questionnaire'
		get 'evaluations/questionnaire_final', to: 'evaluations#questionnaire_final'
		post 'evaluations/record_questionnaire_final', to: 'evaluations#record_questionnaire_final'
		get 'evaluations/thank_you', to: 'evaluations#thank_you'
		get 'evaluations/times_report', to: 'evaluations#times_report'
  	resources :evaluations
	end

  resources :compilation_events
  resources :users
	get 'diagnostic_messages/search', to: 'diagnostic_messages#search'
	get 'examples/random', to: 'examples#random'
  resources :compilers do
  	resources :templates
  	resources :diagnostic_messages do
			get 'embed', to: 'diagnostic_messages#embed'
  		resources :examples do
				#get 'show2', to: 'examples#show2'
			end
		end
	end
  get 'welcome/index'
	post 'welcome/tokenize'	
	post 'welcome/compile'	
	get 'welcome/possible_fixes'	
	get 'welcome/autoexperiment'	
  post 'welcome/compiler'
  get 'welcome/fix_search_control'
	root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails_app/app/models/evaluation.rb
class Evaluation < ApplicationRecord
	belongs_to :user
end

rails_app/app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
	before_action :authenticate_user!
  before_action :require_admin, only: [:show, :new, :edit, :update, :destroy]
  before_action :set_evaluation, only: [:show, :edit, :update, :questionnaire, :record_questionnaire, :tutorial, :record_tutorial_quiz, :tasks, :task, :task_finish, :task_questionnaire, :record_task_questionnaire, :questionnaire_final, :record_questionnaire_final]
	before_action :validate_consent, only: [:questionnaire, :tutorial, :tasks, :task, :task_questionnaire, :questionnaire_final]

	# GET /evaluations/consent
	def consent
		# check if the user has already signed consent	
		e = Evaluation.find_or_create_by(user_id: current_user.id)
		if !e.nil?
			Rails.logger.debug 'e.inspect'
			Rails.logger.debug e.inspect
			if valid_consent(e.consent)
				@consent = e.consent
				Rails.logger.debug 'valid consent'
				render 'consent_signed'
				return
			else 
				Rails.logger.debug 'invalid consent'
			end
		else 
			#error
		end
		# render consent 
	end

	# POST /evaluations/record_consent
	def record_consent
		params.require(:name)
		params.require(:date)
		params.require(:email)
		params.require(:code)
		e = Evaluation.find_by(user_id: current_user.id)
		if !e.nil?
			if valid_consent(e.consent)
				redirect_to evaluations_questionnaire_path, notice: 'Consent recorded.' 
				return
			else
				consent = {}
				consent[:name] = params[:name]
				consent[:date] = params[:date]
				consent[:email] = params[:email]
				consent[:code] = params[:code]
				e.consent = consent
				e.code = params[:code]
				if e.save
					redirect_to evaluations_questionnaire_path, notice: 'Consent recorded.' 
				else
					redirect_to evaluations_consent_path, notice: 'Consent not recorded.' 
				end
				return
			end
		end
		redirect_to evaluations_consent_path, notice: 'Consent not recorded.' 
	end


	# GET /evaluations/questionnaire
	def questionnaire
		#Rails.logger.debug __method__
		#Rails.logger.debug params.inspect
		@education = {}
		@education["Undergraduate (Freshman)"] = "u1"
		@education["Undergraduate (Sophomore)"] = "u2"
		@education["Undergraduate (Junior)"] = "u3"
		@education["Undergraduate (Senior)"] = "u4"
		@education["Graduate - 1st Year"] = "g1"
		@education["Graduate - 2nd Year"] = "g2"
		@education["Graduate - 3rd Year"] = "g3"
		@education["Graduate - 4th Year"] = "g4"
		@education["Graduate - 5th Year"] = "g5"
		@education["Graduate - 6th Year"] = "g6"
		@education["Other (Bachelor's Degree)"] = "bachelors"
		@education["Other (Masters Degree)"] = "masters"
		@education["Other (Ph.D. Degree)"] = "phd"
		@education["Other (All Others)"] = "other"
		@questionnaire = {}
		if !@evaluation.questionnaire.nil?
			@questionnaire = @evaluation.questionnaire
		end
		@started = Time.now
		# render questionnaire		
	end


	# POST /evaluations/record_questionnaire
	def record_questionnaire
		Rails.logger.debug __method__
		Rails.logger.debug params.inspect
		params.permit(:started, :gender, :student, :cppcourse, :cppexpyears, :cppexplevel, :education)
		q = {}
		q[:started] = params[:started]
		q[:education] = params[:education]
		q[:gender] = params[:gender]
		q[:cppcourse] = params[:cppcourse]
		q[:cppexplevel] = params[:cppexplevel]
		q[:cppexpyears] = params[:cppexpyears]
		q[:finished] = Time.now
		@evaluation.questionnaire = q	
		if !@evaluation.save
			redirect_to evaluations_questionnaire_path, notice: 'Questionnaire was not recorded.' 
		else
			redirect_to evaluations_tutorial_path, notice: 'Questionnaire recorded.' 
		end
	end


	# GET /evaluations/tutorial
	def tutorial
		Rails.logger.debug __method__
		@tutorial = {}
		if !@evaluation.tutorial_quiz.nil?
			@tutorial = @evaluation.tutorial_quiz
		end
		@tutorial["started"] = Time.now 
	end

	
	# POST /evaluations/record_tutorial_quiz
	def record_tutorial_quiz
		Rails.logger.debug __method__
		params.permit(:started, :confirmation)
		finished = Time.now
		tutorial = {}
		tutorial["started"] = params[:started]
		tutorial["confirmation"] = params[:confirmation]
		tutorial["finished"] = finished
		@evaluation.tutorial_quiz = tutorial	
		if !@evaluation.save
			redirect_to evaluations_tutorial_path, notice: 'Tutorial was not recorded.' 
		end
		redirect_to evaluations_tasks_path, notice: 'Tutorial quiz recorded.' 
	end


	# GET /evaluations/tasks
	def tasks
		Rails.logger.debug __method__
		max_order = 0
		if !@evaluation.tasks.empty?
			max_order = @evaluation.tasks.max_by { |sid,info| info["order"] }[1]["order"]
		end
		Snippet.order('RANDOM()').each do |s|
			sid_str = s.id.to_s
			if !@evaluation.tasks.has_key?(s.id.to_s)
				Rails.logger.debug "TASK missing #{s.id}"
				g = (rand(0..1) == 0 ? 'control' : 'experimental')
				@evaluation.tasks[sid_str] = {
					"started_at": nil,
					"submitted_at": nil,
					"submission": nil,
					"order": max_order,
					"group": g 
				}
				max_order = max_order + 1
			end # if has_key
		end
		@evaluation.tasks = @evaluation.tasks.sort_by { |sid,info| info["order"] }.to_h
		@evaluation.tasks.each do |sid,info|
			Rails.logger.debug "ORDER = #{info['order']}"
			Rails.logger.debug "Snippet = #{sid}"
			if !task_submitted?(info) 
				Rails.logger.debug 'TASK not submitted'
				@evaluation.next_task = sid # index of next task	
				break
			end
			if !tquestionnaire_complete?(info['questionnaire'])
				Rails.logger.debug 'TQuestionnaire not complete'
				Rails.logger.debug info['questionnaire']
				@evaluation.next_task = sid # index of next task	
				break
			end
			
		end
		@evaluation.save
	end


	def task_submitted?(t)
		return true if !t['timeout'].nil?
		return true if !t['submitted_at'].nil?
		return false
	end

	def tquestionnaire_complete?(q)
		Rails.logger.debug __method__
		Rails.logger.debug q
		return false if q.nil?
		return false if q['compiler_output'].nil?
		return false if q['compiler_output'].to_i == -1
		return false if q['possible_patches'].nil?
		return false if q['possible_patches'].to_i == -1
		return true
	end



	# GET /evaluations/task
	def task
		Rails.logger.debug __method__
		if @evaluation.tasks.empty?
			redirect_to evaluations_tasks_path, notice: 'Redirecting to list of tasks' 
		end
		@snippet = Snippet.find(@evaluation.next_task.to_s)
		sid_str = @snippet.id.to_s 
		@task = @evaluation.tasks[sid_str]
		Rails.logger.debug '@task'
		Rails.logger.debug @task
		if !@task["started_at"].nil? 
			if !@task["submitted_at"].nil?
				Rails.logger.debug 'Task already submitted!'
				redirect_to controller: 'evaluations', action: 'task_questionnaire', notice: 'Task already submitted.', snippet_id: sid_str
				return
			end
			started_at = DateTime.rfc3339(@task["started_at"])	
			Rails.logger.debug 'started_at'
			Rails.logger.debug started_at
			min_diff = (Time.now - started_at.to_time) / 60
			if min_diff > 5
				Rails.logger.debug 'Task time expired!'
				@evaluation.tasks[@snippet.id.to_s]["timeout"] = 't';
				@evaluation.save
				redirect_to controller: 'evaluations', action: 'task_questionnaire', snippet_id: sid_str, notice: 'Time expired'
				return
			end
		else
			@evaluation.tasks[sid_str]["started_at"] = Time.now
		end
		@cmd = "clang++-3.9 -c -Wfatal-errors -stdlib=libc++ -std=c++14"
		@code = @snippet.snippet
		@compiler_output = @snippet.compilation[0]
		@group = @evaluation.tasks[sid_str]['group']
		@evaluation.save
		@started_at = @evaluation.tasks[sid_str]["started_at"]
	end
	

	# POST /evaluations/task_finish
	def task_finish
		Rails.logger.debug __method__
		# TODO: check that submitted_at - started_at <= 5 minutes
		params.require(:code)
		params.require(:snippet_id)
		@snippet = Snippet.find(@evaluation.next_task.to_s)
		if !@snippet.nil?
			if @evaluation.tasks[@snippet.id.to_s]["submitted_at"].nil?
				started_at = DateTime.rfc3339(@evaluation.tasks[@snippet.id.to_s]["started_at"])	
				min_diff = (Time.now - started_at.to_time) / 60
				Rails.logger.debug 'min_diff'
				Rails.logger.debug min_diff
				if min_diff > 5
					@evaluation.tasks[@snippet.id.to_s]["timeout"] = 't';
				else
					@evaluation.tasks[@snippet.id.to_s]["submitted_at"] = Time.now
				end
				@evaluation.tasks[@snippet.id.to_s]["submission"] = params[:code]
				@evaluation.save
			end
		end
		redirect_to controller: 'evaluations', action: 'task_questionnaire', notice: 'Task completed.', snippet_id: @snippet.id
	end


	# GET /evaluations/task_questionnaire
	def task_questionnaire
		Rails.logger.debug __method__
		params.require(:snippet_id)
		@snippet = Snippet.find(params[:snippet_id])
		if @evaluation.tasks[@snippet.id.to_s].nil?
			redirect_to evaluations_tasks_path, notice: 'Invalid task.'	
		end
		if @evaluation.tasks[@snippet.id.to_s]["questionnaire"].nil?
			@questionnaire = {}
			@questionnaire["compiler_output"] = -1 
			@questionnaire["possible_patches"] = -1 
			@evaluation.tasks[@snippet.id.to_s]["questionnaire"] = @questionnaire
			@evaluation.save
		end
		@q= @evaluation.tasks[@snippet.id.to_s]["questionnaire"]
		@group = @evaluation.tasks[@snippet.id.to_s]["group"]
		@cmd = "clang++-3.9 -c -Wfatal-errors -stdlib=libc++ -std=c++14"
		@code = @snippet.snippet
		@compiler_output = @snippet.compilation[0]
		@scale = helpfulness_scale()
	end


	# POST /evaluations/record_task_questionnaire
	def record_task_questionnaire
		Rails.logger.debug __method__
		params.require(:snippet_id)
		params.require(:compiler_output)
		params.require(:possible_patches)
		@evaluation.tasks[params[:snippet_id]]["questionnaire"]["compiler_output"] = params[:compiler_output]
		@evaluation.tasks[params[:snippet_id]]["questionnaire"]["possible_patches"] = params[:possible_patches]
		@evaluation.save
		
		redirect_to evaluations_tasks_path, notice: 'Task questionnaire recorded.'	
	end


	# GET /evaluations/questionnaire_final
	def questionnaire_final
		Rails.logger.debug __method__
		
		@scale = helpfulness_scale()
		@q = {}
		if !@evaluation.questionnaire.nil?
			@q = @evaluation.questionnaire
			#Rails.logger.debug @q
		else

rails_app/app/helpers/evaluations_helper.rb
module EvaluationsHelper

  def task_submitted?(t)
		return true if !t['timeout'].nil?  
		return true if !t['submitted_at'].nil?  
    return false
  end 

  def tquestionnaire_complete?(q)
    return false if q.nil?
    return false if q['compiler_output'].nil?
    return false if q['compiler_output'].to_i == -1
    return false if q['possible_patches'].nil?
    return false if q['possible_patches'].to_i == -1
		return true
  end


end

rails_app/app/views/evaluations/consent.html.erb
<div class="row" style="background-color:#f3f3f3">
<div class="col-sm-12">
<br>
	<div class="text-center">
	<ul class="nav nav-pills nav-fill">
		<li class="nav-item">
		<%= link_to "Consent Form", evaluations_consent_path, class: "nav-link active" %>
		</li>
		<li class="nav-item">
		<%= link_to "Questionnaire", evaluations_questionnaire_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
		<%= link_to "Tutorial", evaluations_tutorial_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
		<%= link_to "Tasks", evaluations_tasks_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
		<%= link_to "Final Questionnaire", evaluations_questionnaire_final_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
		<%= link_to "Exit", evaluations_thank_you_path, class: "nav-link" %>
		</li>
	</ul>
	</div>
<br>
<div class="container">
	<div class="card">
		<div class="card-header">Consent Form</div>
		<div class="card-block">

		<%= render 'consent_form' %>

		<!-- form to print name, date, and email -->
		<%= form_tag(evaluations_record_consent_path, method: "post", class: "form") do %>
			<div class="form-group">
				<%= label_tag(:name, "Type your full name") %>
				<%= text_field_tag(:name, nil, class: "form-control", required: true) %>
			</div>
			<div class="form-group">
				<%= label_tag(:date, "Enter today's date (MM/DD/YYYY)") %>
				<input type="text" id='date' class='form-control' name='date' required='required'>
			</div>
			<div class="form-group">
				<%= label_tag(:email, "Type the email where you want us to send the gift card") %>
				<%= email_field_tag(:email, nil, class: "form-control", required: true) %>
			</div>
			<div class="form-group">
				<%= label_tag(:code, "Enter the code provided to you during recruitment") %>
				<%= text_field_tag(:code, nil, class: "form-control", required: true) %>
			</div>

			<%= submit_tag("Submit", class: "btn btn-primary btn-block") %>
		<% end %>

		</div><!-- card-block -->
	</div><!-- card -->
</div><!-- container -->
<br>
</div>
</div>

<script>
$(document).ready(function(){
	$( "#date" ).datepicker();
});
</script>

rails_app/app/views/evaluations/consent_signed.html.erb
<div class="row" style="background-color:#f3f3f3">
<div class="col-sm-12">
<br>
<div class="text-center">
<ul class="nav nav-pills nav-fill">
	<li class="nav-item">
	<%= link_to "Consent Form", evaluations_consent_path, class: "nav-link active" %>
	</li>
	<li class="nav-item">
	<%= link_to "Entry Questionnaire", evaluations_questionnaire_path, class: "nav-link" %>
	</li>
	<li class="nav-item">
	<%= link_to "Tutorial", evaluations_tutorial_path, class: "nav-link" %>
	</li>
	<li class="nav-item">
	<%= link_to "Tasks", evaluations_tasks_path, class: "nav-link" %>
	</li>
	<li class="nav-item">
	<%= link_to "Final Questionnaire", evaluations_questionnaire_final_path, class: "nav-link" %>
	</li>
	<li class="nav-item">
	<%= link_to "Exit", evaluations_thank_you_path, class: "nav-link" %>
	</li>
</ul>
</div>
<br>

<div class="container">
<div class="card">
	<div class="card-header">Consent Form</div>
	<div class="card-block">

	<%= render 'consent_form' %>
	
	<!-- form to print name, date, and email -->
	<%= form_tag(evaluations_record_consent_path, method: "post", class: "form") do %>
		<div class="form-group">
			<%= label_tag(:name, "Type your full name") %>
			<%= text_field_tag(:name, @consent["name"], class: "form-control", disabled: true) %>
		</div>
		<div class="form-group">
			<%= label_tag(:date, "Enter today's date (MM/DD/YYYY)") %>
			<input type="text" id='date' class='form-control' name='date' disabled='disabled' value="<%= @consent["date"] %>">
		</div>
		<div class="form-group">
			<%= label_tag(:email, "Type the email where you want us to send the gift card") %>
			<%= email_field_tag(:email, @consent["email"], class: "form-control", disabled: true) %>
		</div>
		<div class="form-group">
			<%= label_tag(:code, "Enter the code provided to you during recruitment") %>
			<%= text_field_tag(:code, @consent["code"], class: "form-control", disabled: true) %>
		</div>
	<% end %>

	</div>
</div><!-- card -->
</div><!-- container -->
<br>
</div>
</div>

rails_app/app/views/evaluations/index.html.erb
<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
<br>
<div class="card">
	<div class="card-header">
		<h1>Evaluations</h1>
	</div>
	<div class="card-block">

<table class="table table-sm">
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>User Name (Consent)</th>
      <th>User Email</th>
      <th>Code</th>
      <th>Consent</th>
      <th>Questionnaire</th>
      <th>Tutorial quiz</th>
      <th>Tasks</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |e| %>
      <tr>
        <td><%= link_to e.id, e %></td>
        <td><%= e.user_id %></td>
        <td><%= e.user.name %>(<%= e.consent["name"] %>)</td>
        <td><%= e.user.email %>(<%= e.consent["email"] %>)</td>
        <td><%= e.code %></td>
        <td><%= e.consent.nil? ? 0 : e.consent.size %></td>
        <td><%= e.questionnaire.nil? ? 0 : e.questionnaire.size %></td>
        <td><%= e.tutorial_quiz.nil? ? 0 : e.tutorial_quiz.size %></td>
        <td><%= e.tasks.nil? ? 0 : e.tasks.size %></td>
        <td><%= link_to 'Edit', edit_evaluation_path(e) %></td>
        <td><%= link_to 'Destroy', e, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Times Report', evaluations_times_report_path %>
<%= link_to 'New Evaluation', new_evaluation_path %>
	</div><!-- card-block -->
</div><!-- card -->
</br>

</div>
</div>

rails_app/app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form', evaluation: @evaluation %>

<%= link_to 'Back', evaluations_path %>

rails_app/app/views/evaluations/questionnaire.html.erb
<div class="row" style="background-color:#f3f3f3">
<div class="col-sm-12">
<br>
	<div class="text-center">
	<ul class="nav nav-pills nav-fill">
		<li class="nav-item">
		<%= link_to "Consent Form", evaluations_consent_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
		<%= link_to "Questionnaire", evaluations_questionnaire_path, class: "nav-link active" %>
		</li>
		<li class="nav-item">
		<%= link_to "Tutorial", evaluations_tutorial_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
		<%= link_to "Tasks", evaluations_tasks_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
		<%= link_to "Final Questionnaire", evaluations_questionnaire_final_path, class: "nav-link" %>
		</li>
		<li class="nav-item">
		<%= link_to "Exit", evaluations_thank_you_path, class: "nav-link" %>
		</li>
	</ul>
	</div>
<br>
<div class="card">
<div class="card-header">
Questionnaire
</div>
	<div class="card-block">

	<p>Please answer the following questions.</p>

	<!-- form to print name, date, and email -->
	<%= form_tag(evaluations_record_questionnaire_path, method: "post", class: "form") do %>
		<div class="form-group">
			<%= hidden_field_tag(:started, @questionnaire["started"], class: "form-control", hidden: true) %>
		</div>
		
		
		<div class="form-group">
			<label class="form-label">1. I am a:</label>
			<%= select_tag("education", options_for_select(@education.to_a, @questionnaire["education"]), {:include_blank => true, class: "form-control", required: true}) %>
		</div>


		<div class="form-group">
			<label class="form-label">2. I have _____ years of C++ programming experience.</label>
			<%= number_field_tag(:cppexpyears, @questionnaire["cppexpyears"], class: "form-control", required: true, step: 0.25) %>
		</div>
		
		
		<fieldset class="form-group row">
			<legend class="col-form-legend col-sm-10">3. I have taken an university (or high school) course where C++ programming was required.</legend>
			<div class="col-sm-2">
				<div class="form-check form-check-inline">
					<label class="form-check-label">
						<%= radio_button_tag 'cppcourse', 't', @questionnaire["cppcourse"] == "t", required: true, class: "form-check-input" %>
						True	
					</label>
				</div>
				<div class="form-check form-check-inline">
					<label class="form-check-label">
						<%= radio_button_tag 'cppcourse', 'f', @questionnaire["cppcourse"] == "f", required: true, class: "form-check-input" %>
						False	
					</label>
				</div>
			</div>
		</fieldset>
		
		<fieldset class="form-group row">
			<legend class="col-form-legend col-sm-2">4. I consider myself:</legend>
			<div class="col-sm-10">
			<div class="form-check">
				<label class="form-check-label">
					<%= radio_button_tag 'cppexplevel', '0', @questionnaire["cppexplevel"].to_i == 0, required: true, class: "form-check-input" %>
				Not familiar with C++	
				</label>
			</div>
			<div class="form-check">
				<label class="form-check-label">
					<%= radio_button_tag 'cppexplevel', '1', @questionnaire["cppexplevel"].to_i == 1, required: true, class: "form-check-input" %>
				Slightly familiar with C++	
				</label>
			</div>
			<div class="form-check">
				<label class="form-check-label">
					<%= radio_button_tag 'cppexplevel', '2', @questionnaire["cppexplevel"].to_i == 2, required: true, class: "form-check-input" %>
					Familiar with C++	
				</label>
			</div>
			<div class="form-check">
				<label class="form-check-label">
					<%= radio_button_tag 'cppexplevel', '3', @questionnaire["cppexplevel"].to_i == 3, required: true, class: "form-check-input" %>
					Very familiar with C++	
				</label>
			</div>
			</div>
		</fieldset>

		<fieldset class="form-group row">
			<legend class="col-form-legend col-sm-2">5. I identify as a:</legend>
			<div class="col-sm-10">
				<div class="form-check form-check-inline">
					<label class="form-check-label">
						<%= radio_button_tag 'gender', 'm', @questionnaire["gender"] == "m", required: true, class: "form-check-input" %>
						Male
					</label>
				</div>
				<div class="form-check form-check-inline">
				<label class="form-check-label">
						<%= radio_button_tag 'gender', 'f', @questionnaire["gender"] == "f", required: true, class: "form-check-input" %>
						Female
					</label>
				</div>
				<div class="form-check form-check-inline">
				<label class="form-check-label">
						<input type="radio" class="form-check-input" name="gender" id="optionsRadios3" value="o" required='required'>
						Other
					</label>
				</div>
			</div>
		</fieldset>


		<%= submit_tag("Submit", class: "btn btn-primary btn-block") %>
	<% end %>

	</div><!-- card-block -->
</div><!-- card -->
<br>
</div>
</div>

rails_app/app/views/evaluations/tutorial.html.erb
<div class="row" style="background-color:#f3f3f3">
<div class="col-sm-12">
<br>
<div class="text-center">
<ul class="nav nav-pills nav-fill">
	<li class="nav-item">
	<%= link_to "Consent Form", evaluations_consent_path, class: "nav-link" %>
	</li>
	<li class="nav-item">
	<%= link_to "Entry Questionnaire", evaluations_questionnaire_path, class: "nav-link" %>
	</li>
	<li class="nav-item">
	<%= link_to "Tutorial", evaluations_tutorial_path, class: "nav-link active" %>
	</li>
	<li class="nav-item">
	<%= link_to "Tasks", evaluations_tasks_path, class: "nav-link" %>
	</li>
	<li class="nav-item">
	<%= link_to "Final Questionnaire", evaluations_questionnaire_final_path, class: "nav-link" %>
	</li>
	<li class="nav-item">
	<%= link_to "Exit", evaluations_thank_you_path, class: "nav-link" %>
	</li>
</ul>
</div>
<br>
<div class="card">
<div class="card-header">
Tutorial <small>(Please watch the video for a brief tutorial on our tool.)</small>
</div>
<div class="card-block">

<p>If possible, we recommend you watch in full screen at the highest resolution possible.</p>

<div class="">
<iframe width="560" height="315" src="https://www.youtube.com/embed/JfsGXJSOgeU" frameborder="0" allowfullscreen></iframe>
</div>
<%= form_tag(evaluations_record_tutorial_quiz_path, method: "post", class: "form") do %>
	<div class="form-group">
		<%= hidden_field_tag(:started, @tutorial["started"], class: "form-control", hidden: true) %>
	</div>

	<fieldset class="form-group row">
    <legend class="col-form-legend col-sm-10">I watched and understood the tutorial video.</legend>
		<div class="col-sm-2">
			<div class="form-check form-check-inline">
				<label class="form-check-label">
					<%= radio_button_tag 'confirmation', 't', @tutorial["confirmation"] == "t", required: true, class: "form-check-input" %>
					True	
				</label>
			</div>
			<div class="form-check form-check-inline">
				<label class="form-check-label">
					<%= radio_button_tag 'confirmation', 'f', @tutorial["confirmation"] == "f", required: true, class: "form-check-input" %>
					False	
				</label>
			</div>
    </div>
  </fieldset>
	
  <%= submit_tag("Submit", class: "btn btn-primary btn-block") %>
<% end %>

</div>
<br>
<br>
</div>
</div>