rails_app/config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
	# https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
  resources :snippets

  authenticate :user do
		get 'evaluations/consent', to: 'evaluations#consent'
		post 'evaluations/record_consent', to: 'evaluations#record_consent'
		get 'evaluations/questionnaire', to: 'evaluations#questionnaire'
		post 'evaluations/record_questionnaire', to: 'evaluations#record_questionnaire'
		get 'evaluations/tutorial', to: 'evaluations#tutorial'
		post 'evaluations/record_tutorial_quiz', to: 'evaluations#record_tutorial_quiz'
		get 'evaluations/tasks', to: 'evaluations#tasks'
		get 'evaluations/task', to: 'evaluations#task'
		post 'evaluations/task_finish', to: 'evaluations#task_finish'
		get 'evaluations/task_questionnaire', to: 'evaluations#task_questionnaire'
		post 'evaluations/record_task_questionnaire', to: 'evaluations#record_task_questionnaire'
		get 'evaluations/questionnaire_final', to: 'evaluations#questionnaire_final'
		post 'evaluations/record_questionnaire_final', to: 'evaluations#record_questionnaire_final'
		get 'evaluations/thank_you', to: 'evaluations#thank_you'
		get 'evaluations/times_report', to: 'evaluations#times_report'
  	resources :evaluations
	end

  resources :compilation_events
  resources :users
	get 'diagnostic_messages/search', to: 'diagnostic_messages#search'
	get 'examples/random', to: 'examples#random'
  resources :compilers do
  	resources :templates
  	resources :diagnostic_messages do
			get 'embed', to: 'diagnostic_messages#embed'
  		resources :examples do
				#get 'show2', to: 'examples#show2'
			end
		end
	end
  get 'welcome/index'
	post 'welcome/tokenize'	
	post 'welcome/compile'	
	get 'welcome/possible_fixes'	
	get 'welcome/autoexperiment'	
  post 'welcome/compiler'
  get 'welcome/fix_search_control'
	root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails_app/app/models/diagnostic_message.rb
class DiagnosticMessage < ApplicationRecord
  include PgSearch
  self.per_page = 20


  default_scope { order('bing_search_result_count DESC, examples_count DESC, message ASC') }
	belongs_to :compiler, counter_cache: true
	belongs_to :template, counter_cache: true
	has_many :examples
	has_many :snippets
	belongs_to :creator, class_name: User, foreign_key: 'created_by'
	validates :compiler_id, presence: true

	# 0 (the default) ignores the document length
	# 1 divides the rank by 1 + the logarithm of the document length
	# 2 divides the rank by the document length
	# 4 divides the rank by the mean harmonic distance between extents
	# 8 divides the rank by the number of unique words in document
	# 16 divides the rank by 1 + the logarithm of the number of unique words in document
	# 32 divides the rank by itself + 1
  pg_search_scope :search_by_message, 
									:against => :message, :using => {
                 		:tsearch => {
											:prefix => true, 					# match prefix
											:dictionary => "simple", 	# literal matching, no stemming
											:normalization => (2 + 16),
											:highlight => {
                        :start_sel => '<b>',
                        :stop_sel => '</b>'
                      }
										}
                  }


	# Convert message to search engine query string.
	# Example 1) '_V' does not point into a class 
	# => "does not point into a class"
	# Example 2) expected '(' after 'if' 
	# => "expected" "after"
	# params: none
	def to_query_string
		Rails.logger.debug __method__
		delim = '*****'
		if !self.message.nil?
			message = self.message.dup
			#Rails.logger.debug "message"
			#Rails.logger.debug "#{message.inspect}"
			indices = message.enum_for(:scan,/'/).map { Regexp.last_match.begin(0) }
			if indices.size % 2 != 0
				p_of_i = []
				if !message.index("function's").nil?
					p_of_i = indices[1..2]	
				elsif !message.index("constructor's").nil?
					p_of_i = indices[1..2]	
				elsif !message.index("attribute's").nil?
					p_of_i = indices[0..1]	
				else 
					return nil
				end
				message[p_of_i[0]..p_of_i[1]] = delim
				Rails.logger.debug "message"
				Rails.logger.debug "#{message.inspect}"
			else
				while !message.index("'").nil?
					p_of_i = message.enum_for(:scan,/'/).map { Regexp.last_match.begin(0) }.first(2)
					message[p_of_i[0]..p_of_i[1]] = delim
					Rails.logger.debug "message"
					Rails.logger.debug "#{message.inspect}"
				end
			end
			phrases = message.split(delim)
			phrases.map! { |phrase| phrase.strip } 
			Rails.logger.debug "#{self.message}"
			#Rails.logger.debug "#{message}"
			Rails.logger.debug "#{phrases.inspect}"
			phrases.map! do |phrase|
				if !phrase.blank?
					phrase.prepend('"')
					phrase << '"'
				end
			end
			phrases = phrases.compact
			Rails.logger.debug "#{phrases.inspect}"
			return phrases.join(' ')
		end
		return nil
	end


	
end

rails_app/app/controllers/diagnostic_messages_controller.rb
require 'base64'

class DiagnosticMessagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_diagnostic_message, only: [:show, :edit, :update, :destroy]


  # GET /diagnostic_messages
  # GET /diagnostic_messages.json
  def index
		@compiler = Compiler.find(params[:compiler_id])
		@dms = DiagnosticMessage.where(compiler_id: @compiler.id).paginate(:page => params[:page]).order('id DESC')
  end


	def search
		q = params[:q]
		@empty_query = (q.nil? or q.blank?)
		Rails.logger.debug @empty_query
		if !@empty_query
			@dms = DiagnosticMessage.unscoped.search_by_message(q).with_pg_search_highlight.paginate(:page => params[:page])
		else
			@dms = DiagnosticMessage.unscoped.order("RANDOM()").paginate(:page => params[:page])
		end
	end


  # GET /diagnostic_messages/1
  # GET /diagnostic_messages/1.json
  def show
		@compiler = Compiler.find(params[:compiler_id])
		if @diagnostic_message.nil?
			if !params[:m].nil?
				@message = params[:m] 
			else
				@message = 'Unkown Diagnostic Message'
			end
			render 'unknown'
		end
		@examples = @diagnostic_message.examples.unscoped.paginate(:page => params[:page])
  end


	# GET /diagnostic_messages/1/embed
  # GET /diagnostic_messages/1/embed.json
	def embed
		@compiler = Compiler.find(params[:compiler_id])
		#begin 
    	@diagnostic_message = DiagnosticMessage.find(params[:diagnostic_message_id])
			#Rails.logger.debug @diagnostic_message.inspect
			@compiler = @diagnostic_message.compiler
			#Rails.logger.debug @compiler.inspect
			if !params[:c].nil?
				source_code = Base64.decode64(params[:c])
				#Rails.logger.debug "source_code"
				#Rails.logger.debug source_code	
				# TODO: tokenize using clang
				tokens = source_code.tokenize('c++')
				#Rails.logger.debug "tokens"
				#Rails.logger.debug tokens 
				@diagnostic_message.examples.map do |e|
					#Rails.logger.debug tokens
					e_tokens = e.buggy.tokenize	
					#Rails.logger.debug e_tokens
					a = tokens.size
					b = e_tokens.size
					min = a > b ? a : b
					intersection = tokens & e_tokens
					#Rails.logger.debug 'intersection'
					#Rails.logger.debug intersection
					e.overlap_coefficient = (intersection.size / min.to_f) 
					#Rails.logger.debug 'e.overlap_coefficient'
					#Rails.logger.debug e.overlap_coefficient
					e.overlap_coefficient
				end
				@examples = @diagnostic_message.examples.to_ary
				#Rails.logger.debug "UNSORTED: first = #{@examples[0].id}"
				#Rails.logger.debug "UNSORTED: last = #{@examples[-1].id}"
				@examples.sort_by! do |e| 
					e.overlap_coefficient
				end
				@examples.reverse!
				#Rails.logger.debug "SORTED: first = #{@examples[0].id}"
				#Rails.logger.debug "SORTED: last = #{@examples[-1].id}"
			else
				
			end
		#rescue
		#	@diagnostic_message = nil
		#	if @diagnostic_message.nil?
		#		if !params[:m].nil?
		#			@message = params[:m] 
		#		else
		#			@message = 'Unkown Diagnostic Message'
		#		end
		#		render 'unknown_embed'
		#	end
		#end
	end


  # GET /diagnostic_messages/new
  def new
		@compiler = Compiler.find(params[:compiler_id])
    @diagnostic_message = DiagnosticMessage.new
  end


  # GET /diagnostic_messages/1/edit
  def edit
		@compiler = Compiler.find(params[:compiler_id])
  end


  # POST /diagnostic_messages
  # POST /diagnostic_messages.json
  def create
    @diagnostic_message = DiagnosticMessage.new(diagnostic_message_params)
		@diagnostic_message.compiler_id = params[:compiler_id]
		@diagnostic_message.created_by = current_user.id

    respond_to do |format|
      if @diagnostic_message.save
        format.html { redirect_to compiler_diagnostic_message_url(params[:compiler_id], @diagnostic_message), notice: 'Diagnostic message was successfully created.' }
        format.json { render :show, status: :created, location: @diagnostic_message }
      else
        format.html { render :new }
        format.json { render json: @diagnostic_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostic_messages/1
  # PATCH/PUT /diagnostic_messages/1.json
  def update
    respond_to do |format|
      if @diagnostic_message.update(diagnostic_message_params)
        format.html { redirect_to @diagnostic_message, notice: 'Diagnostic message was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnostic_message }
      else
        format.html { render :edit }
        format.json { render json: @diagnostic_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_messages/1
  # DELETE /diagnostic_messages/1.json
  def destroy
		#TODO: Only admin can delete
		render nothing: true, status: :unauthorized
    @diagnostic_message.destroy
    respond_to do |format|
      format.html { redirect_to diagnostic_messages_url, notice: 'Diagnostic message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostic_message
			begin
      	@diagnostic_message = DiagnosticMessage.find(params[:id])
			rescue
				Rails.logger.debug 'could not find dm'
      	@diagnostic_message = nil
			end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnostic_message_params
      params.require(:diagnostic_message).permit(:compiler_id, :name, :message, :created_by)
    end

end

rails_app/app/helpers/diagnostic_messages_helper.rb
module DiagnosticMessagesHelper
end

rails_app/app/views/diagnostic_messages/_form.html.erb
<%= form_for([@compiler, diagnostic_message]) do |f| %>
  <% if diagnostic_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diagnostic_message.errors.count, "error") %> prohibited this diagnostic_message from being saved:</h2>

      <ul>
      <% diagnostic_message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%# f.label :compiler_id %>
    <%= f.hidden_field :compiler_id, value: @compiler.id %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :message, class: "form-control" %>
  </div>

  <div class="form-group">
    <%# f.label :created_by %>
    <%= f.hidden_field :created_by, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/diagnostic_messages/edit.html.erb
<h1>Editing Diagnostic Message</h1>

<%= render 'form', diagnostic_message: @diagnostic_message %>

<%= link_to 'Show', compiler_diagnostic_message_path(@compiler,@diagnostic_message) %> |
<%= link_to 'Back', compiler_diagnostic_messages_path(@compiler) %>

rails_app/app/views/diagnostic_messages/index.html.erb
<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<br>
<div class="card">
<div class="card-block">
	<p style="margin:0">
	<%= link_to(@compiler.name, compiler_path(@compiler)) %>
	/ Diagnostic Messages
	</p>
</div><!-- card-block -->
</div><!-- card -->


<br>
<div class="card">
<div class="card-block" style="padding-top:0">
<table class="table table-striped table-sm" style="border-top:0">
  <thead>
    <tr>
      <th>ID</th>
      <!--<th>Name</th>-->
      <th>Message</th>
      <th class="text-right">Examples</th>
			<th class="text-right">Bing Search Results</th>
    </tr>
  </thead>

  <tbody>
    <% @dms.each do |dm| %>
      <tr>
        <td><%= link_to dm.id, compiler_diagnostic_message_path(@compiler, dm) %></td>
        <!--<td><%= truncate(dm.name) %></td>-->
        <td><%= truncate(dm.message, length: 50) %></td>
        <td class="text-right"><%= dm.examples.size %></td>
        <td class="text-right"><%= dm.bing_search_result_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="flickr_pagination">
	<div class="page_info">
		<%= page_entries_info @dms %>
	</div>
	<div class="row justify-content-center">
	<%= will_paginate @dms %>
	</div>
</div>

</div><!-- card-block -->
</div><!-- card -->

</div> <!--row -->
</div> <!--col -->

rails_app/app/views/diagnostic_messages/new.html.erb
<h1>New Diagnostic Message</h1>

<%= render 'form', diagnostic_message: @diagnostic_message %>

<%= link_to 'Back', compiler_diagnostic_messages_path(params[:compiler_id]) %>

rails_app/app/views/diagnostic_messages/search.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Help</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
				<p>Search for diagnostic messages.</p>
			</div>
			<!--
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
			-->
    </div>
  </div>
</div>



<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<br>
<div class="card">
	<div class="card-block" style="padding: 0.5rem 0.5rem">
	<p style="margin-bottom:0">
		<% if !@empty_query %>
			Found <b><%= @dms.total_entries %></b> diagnostic messages.
		<% else %>
			No search query entered.  Showing all <b><%= @dms.total_entries %></b> diagnostic messages in random order. 
		<% end%>
		<span class="pull-right"><a href="" data-toggle="modal" data-target="#myModal">Help <i class="fa fa-question-circle" aria-hidden="true"></i></a></span></p>
	</div>
</div>


<br>
<div class="card">
<div class="card-block" style="padding-top:0">
<table class="table table-sm">
  <thead>
    <tr>
      <th>ID</th>
      <th>Message</th>
      <th class="text-right">Examples</th>
			<th class="text-right">Bing Search Results</th>
			<th class="text-right">Template</th>
    </tr>
  </thead>

  <tbody>
    <% @dms.each do |diagnostic_message| %>
      <tr>
        <td><%= link_to diagnostic_message.id, compiler_diagnostic_message_path(diagnostic_message.compiler, diagnostic_message) %></td>
				<% if !@empty_query %>
        	<!--<td><%# diagnostic_message.pg_search_highlight.html_safe %></td>-->
        	<td><%= diagnostic_message.message %></td>
				<% else %>
        	<td><%= diagnostic_message.message %></td>
				<% end %>
        <td class="text-right"><%= diagnostic_message.examples.size %></td>
        <td class="text-right"><%= diagnostic_message.bing_search_result_count %></td>
        <td class="text-right"><%= link_to diagnostic_message.template_id, compiler_template_path(diagnostic_message.compiler, diagnostic_message.template) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="flickr_pagination">
	<div class="page_info">
		<%= page_entries_info @dms %>
	</div>
	<div class="row justify-content-center">
	<%= will_paginate @dms %>
	</div>
</div>

</div>
</div>
<br/>

</div>
</div>

rails_app/app/views/diagnostic_messages/show.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Help</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
				<dl class="row">
					<dt class="col-sm-4">Uncompilable Code</dt>
					<dd class="col-sm-8">This code triggers a compiler error.</dd>

					<dt class="col-sm-4">Uncompilable Code + Fix</dt>
					<dd class="col-sm-8">This code shows the insertions/deletions you can make to the uncompilable code to make it compilable.</dd>

					<dt class="col-sm-4"><ins>Lime text</ins></dt>
					<dd class="col-sm-8">Insert the highlighted characters.</dd>

					<dt class="col-sm-4"><del>Yellow text</del></dt>
					<dd class="col-sm-8">Delete the highlighted characters.</dd>

				</dl>
      </div>
			<!--
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
			-->
    </div>
  </div>
</div>

<div class="row" style="height:3rem;border-bottom:1px solid lightgrey">
	<div class="col-sm-12 my-auto">
  <p style="margin:0">
		<%= link_to(@diagnostic_message.compiler.name, compiler_path(@diagnostic_message.compiler)) %>
		/ <%= link_to("Templates", compiler_templates_path(@diagnostic_message.compiler)) %>
		/ <%= link_to(@diagnostic_message.template.id, compiler_template_path(@diagnostic_message.compiler, @diagnostic_message.template)) %>
		/ <%= link_to("Diagnostic Messages", compiler_diagnostic_messages_path(@diagnostic_message.compiler)) %>
		/ <%= @diagnostic_message.id %>
	</p>
	</div>
</div>

<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<br>
<div class="card">
	<div class="card-block" style="padding: 0.25rem 0.5rem">
		<ul class="list-group list-group-flush">
			<li class="list-group-item justify-content-between" style="padding:0.5rem">
				Message: <span><%= @diagnostic_message.message %></span>
			</li>
			<li class="list-group-item justify-content-between" style="padding:0.5rem">
				Template: <span style="margin:0"><%= @diagnostic_message.template.template %></span>
			</li>
			<li class="list-group-item justify-content-between" style="padding:0.5rem">
				Name: <span style="margin:0"><%= @diagnostic_message.name %></span>
			</li>
			<li class="list-group-item justify-content-between" style="padding:0.5rem">
				Examples: <span style="margin:0"><%= @diagnostic_message.examples.size %></span>
			</li>
			<li class="list-group-item justify-content-between" style="padding:0.5rem">
				Contributor: <span><img src="<%=@diagnostic_message.creator.image_url %>?sz=25" class="rounded-circle float-sm-right"></img></span>
			</li>
		</ul>
	</div>
</div>


<br>
<div class="card">
	<div class="card-block" style="padding: 0.25rem 0.5rem">

	<p style="margin-bottom:0">Showing <span id="ex-count" data-ex_count="<%= @diagnostic_message.examples.size %>" style="font-weight:bold"><%= @diagnostic_message.examples.size %></span> examples fixes.
	<span class="float-sm-right"><a href="" data-toggle="modal" data-target="#myModal">Help <i class="fa fa-question-circle" aria-hidden="true"></i></a></span></p>
	</div>
</div>

<style>
	.card-group {
		border: 1px solid transparent;
	}
	.card-group:hover {
		border: 1px solid black;
	}
	.card-header {
		color: lightgrey;
		/*background-color: white*/
	}

	.card-header p {
		margin: 0;
	}
	.card-group:hover .card .card-header {
		color: black;
	}
	.card-group .card a{
		color: lightgrey;
	}
	.card-group:hover .card a{
		color: #0275d8;
	}
</style>

<br>
<% @diagnostic_message.examples.each_with_index do |ex,i| %>
<div class="card-group" data-example-path="<%= compiler_diagnostic_message_example_url(@diagnostic_message.compiler, @diagnostic_message, ex) %>">
		<div class="card">
		<!--<div class="card-header" style=";padding:0.25rem 1.25rem"><i class="fa fa-times-circle" aria-hidden="true" style="color:red"></i> Buggy Code</div>-->
		<div class="card-header" style=";padding:0.25rem 0.5rem;">
			<p>
			Uncompilable
			</p>
		</div>
		<%= content_tag :pre, ex.buggy, id: "left-editor-#{i}", data: {code: ex.buggy}, style: "height:100%;padding-bottom:0" %>
	</div>

	<div class="card">
		<div class="card-header" style=";padding:0.25rem 0.5rem;">
			<p>
			Fix
			<span class="float-sm-right">
			<%= link_to(compiler_diagnostic_message_example_path(@diagnostic_message.compiler, @diagnostic_message, ex)) do %>
				More <i class="fa fa-info-circle" aria-hidden="true"></i>
			<% end %>
			</span>
			</p>
		</div>
		<%= content_tag :pre, nil, id: "right-editor-#{i}", data: {code: ex.fixed}, style: "height:100%;padding-bottom:0" %>
	</div>
</div>	


<br>
<% end %>
<div class="card">
	<div class="card-header" style=";padding:0.25rem 0.5rem;color:lightgray">Name</div>
	<div class="card-block" style="padding:1rem">
		<%= @diagnostic_message.name %>
	</div>
</div>
<br>

<p>
<%= link_to new_compiler_diagnostic_message_example_path(@diagnostic_message.compiler, @diagnostic_message), class: "btn btn-block btn-primary" do %>
	New Example <i class="fa fa-plus" aria-hidden="true"></i>
<% end %>
</p>

<p>
<%= link_to 'Edit this Diagnostic Message', edit_compiler_diagnostic_message_path(@diagnostic_message.compiler, @diagnostic_message), class: "btn btn-block btn-secondary" %>
</p>
<p>
<%= link_to 'Back to All Diagnostic Messages', compiler_diagnostic_messages_path(@diagnostic_message.compiler), class: "btn btn-block btn-secondary" %>
</p>
<br>

</div>
</div>

<script>
var initDiffView = function(i){
	var val1 = $('#left-editor-'+i).data('code');
	var val2 = $('#right-editor-'+i).data('code');
	//console.log('val1');
	//console.log(val1);
	//console.log('val2');
	//console.log(val2);
	var dmp = new diff_match_patch();
	var diff = dmp.diff_main(val1, val2);
	//console.log(diff);
	var ds = dmp.diff_prettyHtml(diff);
	document.getElementById('right-editor-'+i).innerHTML = ds;
}

$(document).ready(function(){
	var funcs = [];
	var ex_count = parseInt($('#ex-count').data('ex_count'));
	for(var i = 0; i < ex_count; i++){
		(function(j){initDiffView(j)})(i);
	}
});

/*
$('.card-group').on('click', function(){
	var sel = getSelection().toString();
	console.log('sel');
	console.log(sel);
	if(sel.length == 0){
		var url = $(this).data('example-path');
		window.location = url;
	}
});
*/


</script>

rails_app/app/views/diagnostic_messages/unknown.html.erb
<div class="row" style="height:3rem;border-bottom:1px solid lightgrey">
	<div class="col-md-12 my-auto">
  	<p style="margin:0"><%= @compiler.name %>
		/
		<span style="margin:0;font-family:Consolas, Lucida Console, monospace;color:red"><b>Unknown Diagnostic Message</b></span></p>
	</div>
</div>

<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<br>
<div class="card">
	<div class="card-block" style="padding: 0.25rem 0.5rem">
	<p style=""><b><%= @message %></b> was not found in our database of diagnostic messages.</p>
	<p style="margin-bottom:0">If this is an message produced by the compiler, then please consider adding this diagnostic message to our database and providing some good examples.</p>
	</div>
</div>

<br>

<p>
<%= link_to 'Back to All Diagnostic Messages', compiler_diagnostic_messages_path(@compiler), class: "btn btn-block btn-secondary" %>
</p>
<br>

</div>
</div>

rails_app/app/views/diagnostic_messages/unknown_embed.html.erb
<style>
.navbar {
	display: none
}
</style>

<div class="row" style="height:3rem;border-bottom:1px solid lightgrey">
	<div class="col-md-12 my-auto">
  	<p style="margin:0"><%= @compiler.name %>
		/
		<span style="margin:0;font-family:Consolas, Lucida Console, monospace;color:red"><b>Unknown Diagnostic Message</b></span></p>
	</div>
</div>

<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<br>
<div class="card">
	<div class="card-block" style="padding: 0.25rem 0.5rem">
	<p style=""><b><%= @message %></b> was not found in our database of diagnostic messages.</p>
	<p style="margin-bottom:0">If this is an message produced by the compiler, then please consider adding this diagnostic message to our database and providing some good examples.</p>
	</div>
</div>

<br>

<p>
<%= link_to 'Back to All Diagnostic Messages', compiler_diagnostic_messages_path(@compiler), class: "btn btn-block btn-secondary" %>
</p>
<br>

</div>
</div>