rails_app/config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
	# https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
  resources :snippets

  authenticate :user do
		get 'evaluations/consent', to: 'evaluations#consent'
		post 'evaluations/record_consent', to: 'evaluations#record_consent'
		get 'evaluations/questionnaire', to: 'evaluations#questionnaire'
		post 'evaluations/record_questionnaire', to: 'evaluations#record_questionnaire'
		get 'evaluations/tutorial', to: 'evaluations#tutorial'
		post 'evaluations/record_tutorial_quiz', to: 'evaluations#record_tutorial_quiz'
		get 'evaluations/tasks', to: 'evaluations#tasks'
		get 'evaluations/task', to: 'evaluations#task'
		post 'evaluations/task_finish', to: 'evaluations#task_finish'
		get 'evaluations/task_questionnaire', to: 'evaluations#task_questionnaire'
		post 'evaluations/record_task_questionnaire', to: 'evaluations#record_task_questionnaire'
		get 'evaluations/questionnaire_final', to: 'evaluations#questionnaire_final'
		post 'evaluations/record_questionnaire_final', to: 'evaluations#record_questionnaire_final'
		get 'evaluations/thank_you', to: 'evaluations#thank_you'
		get 'evaluations/times_report', to: 'evaluations#times_report'
  	resources :evaluations
	end

  resources :compilation_events
  resources :users
	get 'diagnostic_messages/search', to: 'diagnostic_messages#search'
	get 'examples/random', to: 'examples#random'
  resources :compilers do
  	resources :templates
  	resources :diagnostic_messages do
			get 'embed', to: 'diagnostic_messages#embed'
  		resources :examples do
				#get 'show2', to: 'examples#show2'
			end
		end
	end
  get 'welcome/index'
	post 'welcome/tokenize'	
	post 'welcome/compile'	
	get 'welcome/possible_fixes'	
	get 'welcome/autoexperiment'	
  post 'welcome/compiler'
  get 'welcome/fix_search_control'
	root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails_app/app/views/templates/_form.html.erb
<%= form_for(template) do |f| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :template %>
    <%= f.text_area :template %>
  </div>

  <div class="field">
    <%= f.label :compiler_id %>
    <%= f.number_field :compiler_id %>
  </div>

  <div class="field">
    <%= f.label :created_by %>
    <%= f.number_field :created_by %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

rails_app/app/views/templates/index.html.erb
<div class="row" style="height:3rem;border-bottom:1px solid lightgrey">
	<div class="col-sm-12 my-auto">
  <p style="margin:0">
		<%= link_to(@compiler.name, compiler_path(@compiler)) %>
	/ <%= link_to("Templates", compiler_templates_path(@compiler)) %>
	</p>
	</div>
</div>

<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<br>
<div class="card">
<div class="card-block">
	<ul class="list-group list-group-flush">
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Templates: <span><%= @templates.total_entries %></span>
		</li>
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Templates with Examples: <span style="margin:0"><%= @compiler.templates_with_examples.size %></span>
		</li>
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Templates without Examples: <span style="margin:0"><%= @compiler.templates_without_examples.size %></span>
		</li>
	</ul>
</div><!-- card-block -->
</div><!-- card -->

<br>

<div class="card">
<div class="card-block">
	<table class="table table-sm" style="margin-bottom:0">
		<thead>
			<tr>
				<th>Component</th>
				<th class="text-right">Fix Examples</th>
				<th class="text-right">Covered</th>
				<th class="text-right">Total</th>
				<th class="text-right">Coverage %</th>
			</tr>
		</thead>
	<% JSON.parse(@compiler.summary_by_selected_components.to_s).each do |c,stats|  %>
		<tr>
			<td><%= c %></td>
			<td class="text-right"><%= stats['examples'] %></td>
			<td class="text-right"><%= stats['covered'] %></td>
			<td class="text-right"><%= stats['total'] %></td>
			<td class="text-right"><%= stats['coverage'] %></td>
		</tr>
	<% end %>
	</table>
</div><!-- card-block -->
</div><!-- card -->

<br>

<div class="card">
<div class="card-block" style="padding-top:0">
	<table class="table table-striped table-sm" style="margin-bottom:0">
		<thead>
			<tr>
				<th class="text-right">ID</th>
				<!--<th>Name</th>-->
				<th>Template</th>
				<th class="text-right">Patches</th>
				<th class="text-right">Examples</th>
				<th class="text-right">Diagnostic Messages</th>
				<th class="text-right">Web Search Queries</th>
				<th class="text-right">Search Results</th>
				<th class="text-right">Contributor</th>
			</tr>
		</thead>

		<tbody>
			<% @templates.each do |template| %>
				<tr>
					<td class="text-right"><%= link_to template.id, compiler_template_path(@compiler, template) %></td>
					<!--<td><%= template.name %></td>-->
					<td><%= template.template %></td>
					<td class="text-right"><%= template.patch_count || "nil" %></td>
					<td class="text-right"><%= template.examples_count || "nil" %></td>
					<td class="text-right"><%= template.diagnostic_messages_count %></td>
					<td class="text-right"><%= template.web_search.keys.size %></td>
					<td class="text-right"><%= template.sampled_search_result_count %></td>
					<td class="text-right">
						<a href="<%= user_path(@compiler.creator) %>">
						<% if template.creator.image_url.nil? || template.creator.image_url.blank? %>
							<i class="fa fa-user-circle fa-lg" aria-hidden="true"></i>
						<% else %>
							<img src="<%=template.creator.image_url %>?sz=25" class="rounded-circle"></img>
						<% end %>
						</a>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<br>
	<div class="flickr_pagination">
		<div class="page_info">
			<%= page_entries_info @templates %>
		</div>
		<div class="row justify-content-center">
		<%= will_paginate @templates %>
		</div>
	</div>

</div><!-- card-block -->
</div><!-- card -->

</div> <!--row -->
</div> <!--col -->

rails_app/app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path %>

rails_app/app/views/templates/show.html.erb
<div class="row" style="height:3rem;border-bottom:1px solid lightgrey">
	<div class="col-sm-12 my-auto">
  <p style="margin:0">
		<%= link_to(@template.compiler.name, compiler_path(@template.compiler)) %>
	/ <%= link_to("Templates", compiler_templates_path(@template.compiler)) %>
	</p>
	</div>
</div>


<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<br>
<div class="card">
<div class="card-block">
	<ul class="list-group list-group-flush">
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Name: <span><%= @template.name %></span>
		</li>
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Template: <span style="margin:0"><%= @template.template.blank? ? "<Blank>" : @template.template %></span>
		</li>
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Patches: <span><%= @template.patch_count %></span>
		</li>
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Diagnostic Messages: <span><%= @template.diagnostic_messages.size %></span>
		</li>
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Examples: <span><%= @template.examples.size %></span>
		</li>
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Web Search Queries: <span><%= @template.web_search.keys.size %></span>
		</li>

		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Sampled Query String: <span><%= @template.sampled_query.blank? ? "<NONE>" : @template.sampled_query %></span>
		</li>
		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			Sampled Search Results Count: <span><%= @template.sampled_search_result_count %></span>
		</li>

		<li class="list-group-item justify-content-between" style="padding:0.5rem">
			<% if user_signed_in? && (current_user.id == @compiler.creator.id) %>
				<%= link_to 'Edit', edit_compiler_path(@compiler) %> |
				<%= link_to 'Back', compilers_path %>
			<% end %>
		</li>
	</ul>

</div><!-- card-block -->
<% if user_signed_in? && current_user.id == 1 %>
<div class="card-footer">
<%= link_to 'Edit', edit_compiler_template_path(@template.compiler, @template) %>
</div>
<% end %>
</div><!-- card -->

<br>

<div class="card">
<div class="card-block">
	<table class="table table-sm" style="margin-bottom:0">
		<thead>
			<tr>
				<th>Patch</th>
				<th class="text-right">Fix Examples</th>
			</tr>
		</thead>
	<% @template.patches.each do |p,examples|  %>
		<tr>
			<td><%= p.nil? ? '<BLANK>' : p %></td>
			<td class="text-right"><%= examples %></td>
		</tr>
	<% end %>
	</table>
</div><!-- card-block -->
</div><!-- card -->




<br>
<div class="card">
<div class="card-block" style="padding-top:0">
<table class="table table-striped table-sm">
  <thead>
    <tr>
      <th>ID</th>
      <!--<th>Name</th>-->
      <th>Diagnostic Messages</th>
      <th class="text-right">Examples</th>
			<th class="text-right">Search Results</th>
    </tr>
  </thead>

  <tbody>
    <% @dms.each do |diagnostic_message| %>
      <tr>
        <td><%= link_to diagnostic_message.id, compiler_diagnostic_message_path(@compiler, diagnostic_message) %></td>
        <!--<td><%= truncate(diagnostic_message.name) %></td>-->
        <td><%= truncate(diagnostic_message.message, length: 80) %></td>
        <td class="text-right"><%= diagnostic_message.examples.size %></td>
        <td class="text-right"><%= diagnostic_message.bing_search_result_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="flickr_pagination">
	<div class="page_info">
		<%= page_entries_info @dms %>
	</div>
	<div class="row justify-content-center">
	<%= will_paginate @dms %>
	</div>
</div>

</div><!-- card-block -->
</div><!-- card -->


</div> <!--row -->
</div> <!--col -->