rails_app/config/routes.rb
Rails.application.routes.draw do
	devise_for :users, :controllers => { :registrations => 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
	# https://github.com/plataformatec/devise/wiki/How-To:-Define-resource-actions-that-require-authentication-using-routes.rb
  resources :snippets

  authenticate :user do
		get 'evaluations/consent', to: 'evaluations#consent'
		post 'evaluations/record_consent', to: 'evaluations#record_consent'
		get 'evaluations/questionnaire', to: 'evaluations#questionnaire'
		post 'evaluations/record_questionnaire', to: 'evaluations#record_questionnaire'
		get 'evaluations/tutorial', to: 'evaluations#tutorial'
		post 'evaluations/record_tutorial_quiz', to: 'evaluations#record_tutorial_quiz'
		get 'evaluations/tasks', to: 'evaluations#tasks'
		get 'evaluations/task', to: 'evaluations#task'
		post 'evaluations/task_finish', to: 'evaluations#task_finish'
		get 'evaluations/task_questionnaire', to: 'evaluations#task_questionnaire'
		post 'evaluations/record_task_questionnaire', to: 'evaluations#record_task_questionnaire'
		get 'evaluations/questionnaire_final', to: 'evaluations#questionnaire_final'
		post 'evaluations/record_questionnaire_final', to: 'evaluations#record_questionnaire_final'
		get 'evaluations/thank_you', to: 'evaluations#thank_you'
		get 'evaluations/times_report', to: 'evaluations#times_report'
  	resources :evaluations
	end

  resources :compilation_events
  resources :users
	get 'diagnostic_messages/search', to: 'diagnostic_messages#search'
	get 'examples/random', to: 'examples#random'
  resources :compilers do
  	resources :templates
  	resources :diagnostic_messages do
			get 'embed', to: 'diagnostic_messages#embed'
  		resources :examples do
				#get 'show2', to: 'examples#show2'
			end
		end
	end
  get 'welcome/index'
	post 'welcome/tokenize'	
	post 'welcome/compile'	
	get 'welcome/possible_fixes'	
	get 'welcome/autoexperiment'	
  post 'welcome/compiler'
  get 'welcome/fix_search_control'
	root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails_app/app/models/example.rb
require 'digest/sha1'
require 'open3'

class Example < ApplicationRecord
  default_scope { order('char_length(fixed) ASC, fixed ASC') }
	belongs_to :diagnostic_message, counter_cache: true
	belongs_to :creator, class_name: User, foreign_key: 'created_by'
	belongs_to :template
	belongs_to :compiler
	validates :fixed, presence: true
	validates :buggy, presence: true
	#validates :fixed_tokens_sha1, presence: true
	#validates :buggy_tokens_sha1, presence: true, uniqueness: true
	#validates_uniqueness_of :buggy_tokens_sha1
  #before_validation :tokenize_and_hash
	validate :fix_uniqueness
	attr_accessor :overlap_coefficient
	attr_accessor :levenshtein_distance
	attr_accessor :diff

	def fix_uniqueness
		Rails.logger.debug __method__
		tokenize_and_hash
		Rails.logger.debug self.inspect
		if !self.buggy_tokens_sha1.nil?
			e = Example.find_by(diagnostic_message_id: self.diagnostic_message_id, buggy_tokens_sha1: self.buggy_tokens_sha1, fixed_tokens_sha1: self.fixed_tokens_sha1)
			if !e.nil?
				if e.id != self.id
					Rails.logger.debug e.inspect
					errors.add(:fix_uniqueness, "Similar fix already exists. See example ##{e.id}.")
				end
			end
		else
			errors.add(:buggy_tokens_sha1, "Buggy code sha1 missing.")
		end
	end


	def tokenize_and_hash
		Rails.logger.debug __method__
		self.buggy_tokens = self.buggy.tokenize()
		self.fixed_tokens = self.fixed.tokenize()
		token_str = self.buggy_tokens.join(' ')
		self.buggy_tokens_sha1 = Digest::SHA1.digest(token_str)	
		token_str = self.fixed_tokens.join(' ')
		self.fixed_tokens_sha1 = Digest::SHA1.digest(token_str)	
	end


	# Tokenize both buggy and fixed code and save
	def tokenize_buggy_and_fixed
		self.buggy_tokens = self.buggy.tokenize()
		self.fixed_tokens = self.fixed.tokenize()
		self.save
	end


	# Tokenize buggy code and save
	def tokenize_buggy
		self.buggy_tokens = self.buggy.tokenize()
		self.save
	end


	# Tokenize fixed code and save
	def tokenize_fixed
		self.fixed_tokens = self.fixed.tokenize()
		self.save
	end


	def hash_buggy_and_fixed_tokens
		token_str = self.buggy_tokens.join(' ')
		self.buggy_tokens_sha1 = Digest::SHA1.digest(token_str)	
		token_str = self.fixed_tokens.join(' ')
		self.fixed_tokens_sha1 = Digest::SHA1.digest(token_str)	
		self.save
	end

	def hash_buggy_tokens
		token_str = self.buggy_tokens.join(' ')
		self.buggy_tokens_sha1 = Digest::SHA1.digest(token_str)	
		self.save
	end

	def hash_fixed_tokens
		token_str = self.fixed_tokens.join(' ')
		self.fixed_tokens_sha1 = Digest::SHA1.digest(token_str)	
		self.save
	end

	def compile
		self.buggy_compilation_output = self.buggy.compile[0]
		self.buggy_compilation_status = self.buggy.compile[1].exitstatus
		self.fixed_compilation_output = self.fixed.compile[0]
		self.fixed_compilation_status = self.fixed.compile[1].exitstatus
		self.save
	end


	def compile_and_save
		cmd = "clang++-3.9 -c -Wfatal-errors -std=c++14 -stdlib=libc++ -x c++ -"
		stdout_and_stderr_str, status = Open3.capture2e(cmd, stdin_data: self.buggy)
		Rails.logger.debug stdout_and_stderr_str
		self.compiler_output = stdout_and_stderr_str
		self.save
	end


	def compile_and_save_fixed
		cmd = "clang++-3.9 -c -Wfatal-errors -std=c++14 -stdlib=libc++ -x c++ -"
		stdout_and_stderr_str, status = Open3.capture2e(cmd, stdin_data: self.fixed)
		Rails.logger.debug stdout_and_stderr_str
		self.compiler_output_fixed = stdout_and_stderr_str
		self.save
	end



	def update_diagnostic_message_id
		Rails.logger.debug __method__
		return false if !self.anomalous_dm?
		extracted_message = self.extract_diagnostic_message(self.compiler_output)
		# search for dm to get id
		dm = DiagnosticMessage.find_by(message: extracted_message)
		Rails.logger.debug 'dm.inspect'
		Rails.logger.debug dm.inspect
		if dm.nil?
			admin = User.find(1)
			compiler_id = self.diagnostic_message.compiler_id
			dm = DiagnosticMessage.create(compiler_id: compiler_id, message:extracted_message, created_by: admin.id)
			Rails.logger.debug 'dm.inspect'
			Rails.logger.debug dm.inspect
		end
		self.diagnostic_message_id = dm.id	
		if self.save
			Rails.logger.debug 'SUCCESS: Updated diagnostic_message_id.'	
			return true
		else
			Rails.logger.debug 'self.errors.inspect'
			Rails.logger.debug self.errors.inspect
		end
		
		Rails.logger.debug 'ERROR: Failed to update diagnostic_message_id.'	
		return false
	end


	def extract_diagnostic_message(compiler_output)
		Rails.logger.debug __method__
		return nil if compiler_output.nil?
		# parse line with "error:" to get diagnostic message
		dm = ""
		compiler_output.each_line do |line|
			if line =~ /error\:/ 
				dm = line.split("error:")[1].strip
			end                                                                             
		end 

		return dm		
	end


	def anomalous_dm?
		Rails.logger.debug __method__
		a = self.extract_diagnostic_message(self.compiler_output) 
		if !a.nil?
			b = self.diagnostic_message.message
			Rails.logger.debug 'a = self.extract_diagnostic_message'
			Rails.logger.debug a.inspect
			Rails.logger.debug 'b = self.diagnostic_message.message'
			Rails.logger.debug b.inspect
			Rails.logger.debug 'a != b'
			Rails.logger.debug a != b
			return a != b
		end
		return false
	end

	def bad_fix?
		Rails.logger.debug __method__
		return self.fixed_compilation_status == 0
	end

	def diff_tokens
		change = 0
		token = ""
		if self.buggy_tokens.size > self.fixed_tokens.size
			change = -1 # delete
			token = self.buggy_tokens.subtract_once(self.fixed_tokens)
		elsif self.buggy_tokens.size < self.fixed_tokens.size
			change = 1 # insert
			token = self.fixed_tokens.subtract_once(self.buggy_tokens)
		else
			change = 0 # replace	
			buggy_token = self.buggy_tokens.subtract_once(self.fixed_tokens)
			fixed_token = self.fixed_tokens.subtract_once(self.buggy_tokens)
			token = buggy_token + fixed_token
		end
		self.token_diff_change = change
		self.token_diff_token = token
	end


	def set_patch
		self.patch = self.token_diff_message
		self.save	
	end


	def token_diff_message
		#Rails.logger.debug __method__
		#Rails.logger.debug self.id
		message = "Cannot compute token diff."
		self.diff_tokens
		op = ''

		if !self.token_diff_change.nil?
			message = ""
			if self.token_diff_change == -1	
				op = "Delete"
			elsif self.token_diff_change == 1
				op = "Insert"
			elsif self.token_diff_change == 0
				op = "Replace"
			end
			#Rails.logger.debug self.token_diff_token.inspect
			tokens = JSON.parse(self.token_diff_token)
			#Rails.logger.debug tokens.inspect
			#Rails.logger.debug tokens.inspect
			if self.token_diff_change == 0
				message = op + ' ' + tokens.join(' with ')
			else
				tokens.each do |t|
					message += "#{op} #{t}, "
				end
				message[-2..-1] = ''
			end
		end

		return message
	end


	def format
		newb = self.buggy.format('Chromium')
		newf = self.fixed.format('Chromium')
		return false if newb == "No such file or directory"	
		return false if newf == "No such file or directory"	
		self.buggy = newb 
		self.fixed = newf
	end


	def format_and_save
		self.format
		self.save
	end


	# For a given piece of code, find all related examples
	# Related = trigger the same compiler error template 
	def self.related(message)
		Rails.logger.debug __method__
		examples = []

		# Find examples that trigger same error or error template 
		dm = DiagnosticMessage.find_by(message: message)
		if !dm.nil? and !dm.template_id.nil?
			template = Template.find(dm.template_id)
			if !template.nil?
				Rails.logger.debug 'template.diagnostic_messages.size'
				Rails.logger.debug template.diagnostic_messages.size
				examples = template.examples
				examples = examples.to_ary
			else # template.nil?
				Rails.logger.debug 'ERROR: template.nil?'	
				Rails.logger.debug 'dm.inspect'	
				Rails.logger.debug dm.inspect
			end #!template.nil?
		else # @dm.nil?	
			template_temp = message.to_template
			Rails.logger.debug 'template_temp.inspect'
			Rails.logger.debug template_temp.inspect
			templates = Template.unscoped.search_by_template(template_temp)
			Rails.logger.debug 'templates.inspect'
			Rails.logger.debug templates.inspect
			templates.each do |t|
				examples.concat(t.examples)
			end
		end # if !@dm.nil?
		return examples
	end #related


	def self.related_grouped_by_patch(message)
		Rails.logger.debug __method__
		examples = []
		patches = {}
		key = Digest::SHA1.hexdigest("examples/related/#{message}")
		Rails.logger.debug 'key'
		Rails.logger.debug key
		Rails.cache.fetch(key, compress: true) do
			examples = Example.related(message)
			# GROUP examples
			patches = examples.group_by { |e| e.patch }	
			patches.to_h
		end
	end



	def self.same_token_size
		es = []
		Example.unscoped.order(:id).each do |e|
			if e.buggy_tokens.size == e.fixed_tokens.size
				es << e
			end
		end	
		return es
	end


	def self.same_token_size_summary
		es = self.same_token_size
		patches = {}
		es.each do |e|
			if patches.has_key?(e.patch)
				patches[e.patch] << e.id
			else
				patches[e.patch] = []
			end
		end	
		return patches
	end


	def set_sizes
		self.buggy_loc = buggy.lines.count
		self.fixed_loc = fixed.lines.count
		self.buggy_tokens_size = self.buggy_tokens.size
		self.fixed_tokens_size = self.fixed_tokens.size
		self.save
	end
	#private


	def self.buggy_not_buggy
		es = Example.where(buggy_compilation_output:'',buggy_compilation_status:0)	
		return es
	end

	def set_diff
		Diffy::Diff.new(self.buggy,self.fixed).to_s(:html)
	end


end

rails_app/app/controllers/examples_controller.rb
# sort examples using overlap coefficient and bigrams
#require 'diffy'
 

class ExamplesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_example, only: [:show, :edit, :update, :destroy]

  # GET /examples
  # GET /examples.json
  def index
		@compiler = Compiler.find(params[:compiler_id])
		@dm = DiagnosticMessage.find(params[:diagnostic_message_id])
    @examples = Example.all
  end

	# GET /examples/random
  # GET /examples/random.json
	def random
		examples = Example.unscoped.select(:id, :buggy).order("RANDOM()").limit(1)
		@example = examples.first
		Rails.logger.debug @example.inspect
		@example.buggy = "//Example #{@example.id}\n#{@example.buggy}" 
		Rails.logger.debug @example.inspect

		respond_to do |format|
			format.json { render json: @example }
			#format.js { render json: @example, content_type: 'application/json' }
			#format.js { render json: @example, content_type: 'application/json' }
		end
	end

  # GET /examples/1
  # GET /examples/1.json
  def show
		@compiler = Compiler.find(params[:compiler_id])
		@dm = DiagnosticMessage.find(params[:diagnostic_message_id])
		@diff = Diffy::Diff.new(@example.buggy, @example.fixed).to_s(:html)
	end





  # GET /examples/1/show2
  # GET /examples/1/show2.json (?)
  def show2
    @example = Example.find(params[:example_id])
		@compiler = Compiler.find(params[:compiler_id])
		@dm = DiagnosticMessage.find(params[:diagnostic_message_id])
  end

  # GET /examples/new
  def new
		Rails.logger.debug 'ExamplesController.new'
		@compiler = Compiler.find(params[:compiler_id])
		Rails.logger.debug '@compiler.inspect'
		Rails.logger.debug @compiler.inspect
		@dm = DiagnosticMessage.find(params[:diagnostic_message_id])
		Rails.logger.debug '@dm.inspect'
		Rails.logger.debug @dm.inspect
    @example = Example.new
		Rails.logger.debug '@example.inspect'
		Rails.logger.debug @example.inspect
  end

  # GET /examples/1/edit
  def edit
		if current_user.id != @example.creator.id
			redirect_back(fallback_location: root_url)
		end
		@compiler = Compiler.find(params[:compiler_id])
		@dm = DiagnosticMessage.find(params[:diagnostic_message_id])
  end

  # POST /examples
  # POST /examples.json
  def create
		Rails.logger.debug 'ExamplesController.create'
    @example = Example.new(example_params)
		@example.diagnostic_message_id = params[:diagnostic_message_id]
		@example.created_by = current_user.id
		@compiler = Compiler.find(params[:compiler_id])
		@dm = DiagnosticMessage.find(params[:diagnostic_message_id])


    respond_to do |format|
      if @example.save
        format.html { redirect_to compiler_diagnostic_message_example_url(params[:compiler_id], params[:diagnostic_message_id], @example), notice: 'Example was successfully created.' }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1
  # PATCH/PUT /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to compiler_diagnostic_message_example_url(params[:compiler_id], params[:diagnostic_message_id], @example), flash: {notice: 'Example was successfully updated.' }}
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1
  # DELETE /examples/1.json
  def destroy
		if current_user.id != @example.creator.id	
			render nothing: true, status: :unauthorized
		end
    @example.destroy
    respond_to do |format|
      format.html { redirect_to examples_url, notice: 'Example was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def example_params
      params.require(:example).permit(:diagnostic_message_id, :buggy, :fixed, :created_by)
    end
end

rails_app/app/helpers/examples_helper.rb
module ExamplesHelper
end

rails_app/app/views/examples/edit.html.erb
<h1>Editing Example</h1>

<%= render 'form', example: @example %>

<%= link_to 'Show', compiler_diagnostic_message_example_path(@compiler, @dm, @example) %> |
<%= link_to 'Back', compiler_diagnostic_message_examples_path(@compiler, @dm) %>

rails_app/app/views/examples/index.html.erb
<h1>Examples</h1>

<table class="table table-sm">
  <thead>
    <tr>
      <th>Diagnostic message</th>
      <th>Buggy</th>
      <th>Fixed</th>
      <th>Created by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.diagnostic_message_id %></td>
        <td><%= example.buggy %></td>
        <td><%= example.fixed %></td>
        <td><%= example.created_by %></td>
        <td><%= link_to 'Show', compiler_diagnostic_message_example_path(@compiler, @dm, example) %></td>
        <td><%= link_to 'Edit', edit_compiler_diagnostic_message_example_path(@compiler, @dm, example) %></td>
        <td><%= link_to 'Destroy', compiler_diagnostic_message_example_path(@compiler, @dm, example), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_compiler_diagnostic_message_example_path(@compiler, @dm) %>

rails_app/app/views/examples/new.html.erb
<h1>New Example</h1>

<%= render 'form', example: @example %>

<%= link_to 'Back', compiler_diagnostic_message_examples_path(@compiler, @dm) %>

rails_app/app/views/examples/show.html.erb
<style>

@media (min-width: 576px) {
	.card-columns {
		column-count: 2;
	}
}

@media (min-width: 768px) {
	.card-columns {
		column-count: 2;
	}
}

@media (min-width: 992px) {
	.card-columns {
		column-count: 2;
	}
}

@media (min-width: 1200px) {
	.card-columns {
		column-count: 2;
	}
}

.card-header {
	padding-left: 0.75rem;
	padding-right: 0.75rem;
}

.card-footer {
	padding-left: 1.0rem;
	padding-right: 1.0rem;
}

.card-block {
	padding-left: 0.25rem;
	padding-right: .25rem;
	padding-top: 0.5rem;
	padding-bottom: 0.5rem;
}
  
</style>


<div class="row" style="height:3rem;border-bottom:1px solid lightgrey">
	<div class="col-sm-12 my-auto">
  	<p style="margin-bottom:0">
		<%= link_to(@compiler.name, compiler_path(@compiler)) %>
		/ <%= link_to 'Templates', compiler_templates_path(@example.diagnostic_message.compiler) %>
		/ <%= link_to @example.diagnostic_message.template.id, compiler_template_path(@example.diagnostic_message.compiler, @example.diagnostic_message.template) %>
		/ <%= link_to 'Diagnostic Messages', compiler_diagnostic_messages_path(@example.diagnostic_message.compiler) %>
		/ <%= link_to @example.diagnostic_message.id, compiler_diagnostic_message_path(@example.diagnostic_message.compiler, @example.diagnostic_message.id) %>
		/ <span style="font-family:Consolas, Lucida Console, monospace;color:red"><b><%= @example.diagnostic_message.message %></b></span>
		</p>
	</div>
</div>


<div class="row" style="background-color:#f3f3f3">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">


<br>
<div class="card-columns">
	<div class="card">
		<div class="card-header" style="background-color:transparent">
			Buggy
			<span class="pull-right"><%= @example.buggy_loc.nil? ? 'Unknown LOC' : @example.buggy_loc  %></span>
		</div>
		<div class="card-block">
			<%= content_tag :pre, @example.buggy, id: "left-editor", data: {code: @example.buggy}, style: "height:100%;" %>
		</div>
	</div>

	<br>
	<div class="card">
		<div class="card-header" style="background-color:transparent">
			Buggy Compilation Output
			<span class="pull-right"><%= @example.buggy_compilation_status.nil? ? 'Not Compiled yet.' : @example.buggy_compilation_status  %></span>
		</div>
		<div class="card-block">
			<% if !@example.buggy_compilation_output.nil? %>
				<%= content_tag :pre, "$ clang++-3.9 -c -Wfatal-errors -std=c++14 -stdlib=libc++\n" + @example.buggy_compilation_output %>
			<% end %>
		</div>
		<div class="card-footer" style="background-color:transparent">
			<span style="color:red"><%= @example.extract_diagnostic_message(@example.buggy_compilation_output) %></span>
		</div>
	</div>

	<br>
	<div class="card">
		<div class="card-header" style="background-color:transparent">
			Fix
			<span class="pull-right"><%= @example.fixed_loc.nil? ? 'Unknown LOC' : @example.fixed_loc  %></span>
		</div>
		<div class="card-block">
			<%= content_tag :pre, nil, id: "right-editor", data: {code: @example.fixed}, style: "height:100%;" %>
		</div>
	</div>

	<br>
	<div class="card">
		<div class="card-header" style="background-color:transparent">
			Fixed Compilation Output
			<span class="pull-right"><%= @example.fixed_compilation_status.nil? ? 'Not Compiled yet.' : @example.fixed_compilation_status  %></span>
		</div>
		<div class="card-block">
			<% if !@example.fixed_compilation_output.nil? %>
				<%= content_tag :pre, "$ clang++-3.9 -c -Wfatal-errors -std=c++14 -stdlib=libc++\n" + @example.fixed_compilation_output %>
			<% end %>
		</div>
		<div class="card-footer" style="background-color:transparent">
			<span style="color:red"><%= @example.extract_diagnostic_message(@example.fixed_compilation_output) %></span>
		</div>
	</div>

</div><!-- card-columns -->


<br>
<div class="card-deck">
	<div class="card">
		<div class="card-header" style="background-color:transparent">Uncompilable Code Tokens</div>
		<div class="card-block" style="line-height:2rem">
		<% @example.buggy_tokens.each do |t| %>
			<span style="border:1px solid lightgrey; padding:0.25rem;line-height:1.5rem"><%= t %></span>
		<% end %>
		</div>
		<div class="card-header" style="background-color:transparent">
			<%= @example.buggy_tokens_size || "Unknown Number" %> Tokens
		</div>
	</div>

	<div class="card">
		<div class="card-header" style="background-color:transparent">Fixed Code Tokens</div>
		<div class="card-block" style="line-height:2rem">
		<% @example.fixed_tokens.each do |t| %>
			<span style="border:1px solid lightgrey; padding:0.25rem;line-height:1.5rem"><%= t %></span>
		<% end %>
		</div>
		<div class="card-header" style="background-color:transparent">
			<%= @example.fixed_tokens_size || "Unknown Number" %> Tokens
		</div>
	</div>
</div>	

<br>

<!--Tokenizer Output -->
<div class="card-deck">
	<div class="card" style="overflow:auto">
		<div class="card-header" style="background-color:transparent">Buggy Tokenizer Output</div>
		<div class="card-block" style="line-height:2rem">
		<%= content_tag :pre, "$ clang++-3.9 -cc1 -dump-tokens -Wfatal-errors -stdlib=libc++ -std=c++14\n" + @example.buggy.tokenizer_output %>

		</div>
	</div>

	<div class="card" style="overflow:auto">
		<div class="card-header" style="background-color:transparent">Fixed Tokenizer Output</div>
		<div class="card-block" style="line-height:2rem">
		<%= content_tag :pre, "$ clang++-3.9 -cc1 -dump-tokens -Wfatal-errors -stdlib=libc++ -std=c++14\n" + @example.fixed.tokenizer_output %>
		</div>
	</div>
</div>	


<br>

<div class="card">
<div class="card-header">Patch</div>
<div class="card-block" style="padding-top: 0.75rem;padding-bottom: 0.75rem">
<%= @example.patch %>
</div>
</div>


<br>




<style>
.diff{overflow:auto;}
.diff ul{background:#fff;overflow:auto;font-size:13px;list-style:none;margin:0;padding:0;display:table;width:100%;}
.diff del, .diff ins{display:block;text-decoration:none;}
.diff li{padding:0; display:table-row;margin: 0;height:1em;}
.diff li.ins{background:#dfd; color:#080}
.diff li.del{background:#fee; color:#b00}
.diff li:hover{background:#ffc}
/* try 'whitespace:pre;' if you don't want lines to wrap */
.diff del, .diff ins, .diff span{white-space:pre-wrap;font-family:courier;}
.diff del strong{font-weight:normal;background:#fcc;}
.diff ins strong{font-weight:normal;background:#9f9;}
.diff li.diff-comment { display: none; }
.diff li.diff-block-info { background: none repeat scroll 0 0 gray; }
</style>



<div class="diff">
	<%= @diff.html_safe %>
</div>


<br>

<div class="card">
<div class="card-block" style="padding-top: 0.75rem;padding-bottom: 0.75rem">
<div class="media">
	<img src="<%= @example.creator.image_url %>?sz=50" class="d-flex mr-3" alt="<%= @example.creator.name %>">
  <div class="media-body">
    <h6 class="mt-0"><%= link_to @example.creator.email, user_path(@example.creator) %></h6>
		<small><%= @example.created_at.strftime('%B %e at %l:%M %p') %></small>
  </div>
</div>
</div>
</div>

<br>

<% if user_signed_in? %>
<% if current_user.id == @example.created_by %>
<p>
<%= link_to 'Edit', edit_compiler_diagnostic_message_example_path(@compiler, @dm, @example), class: "btn btn-block btn-secondary" %> 
</p>
<% end %>
<p>
<%= link_to 'Back to all examples', compiler_diagnostic_message_examples_path(@compiler, @dm) , class: "btn btn-block btn-secondary" %>
</p>
<% end %>

</div>
</div>

<script>
var ready = function(){
	var val1 = $('#left-editor').data('code');
	var val2 = $('#right-editor').data('code');
	console.log('val1');
	console.log(val1);
	console.log('val2');
	console.log(val2);
	var dmp = new diff_match_patch();
	var diff = dmp.diff_main(val1, val2);
	console.log(diff);
	var ds = dmp.diff_prettyHtml(diff);
	document.getElementById('right-editor').innerHTML = ds;
}

$(document).ready(ready);

</script>